### ISSUE TITLE
Depends does not work

### ISSUE THREAD

**Issue by delijati** [KiraPC/fastapi-router-controller#1] opened 2021-03-30 20:52 UTC
If i add Depends to the class it does not resolve. See `print(self.x.create())`

```python
import unittest

from pydantic import BaseModel
from fastapi_router_controller import Controller, ControllersTags
from fastapi import APIRouter, Depends, FastAPI, Query, status
from fastapi.responses import JSONResponse
from fastapi.testclient import TestClient

router = APIRouter()

controller = Controller(router, openapi_tag={"name": "sample_controller"})


class SampleObject(BaseModel):
    id: str


def get_x():
    class Foo:
        def create(self):
            return "XXX"

    return Foo()


# With the "resource" decorator define the controller Class linked to the Controller router arguments
@controller.resource()
class SampleController:
    x = Depends(get_x)

    @controller.route.get(
        "/", tags=["sample_controller"], summary="return a sample object",
        response_model=SampleObject
    )
    def sample_get_request(
        self,
        id: str = Query(..., title="itemId", description="The id of the sample object"),
    ):
        print(self.x.create())
        return SampleObject(id=id)


def create_app():
    app = FastAPI(
        title="A sample application using fastapi_router_controller",
        version="0.1.0",
        openapi_tags=ControllersTags,
    )

    sample_controller = SampleController()

    app.include_router(sample_controller.router())
    return app


class TestRoutes(unittest.TestCase):
    def setUp(self):
        app = create_app()
        self.client = TestClient(app)

    def test_root(self):
        response = self.client.get("/?id=12")
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.json(), {"id": "12"})


if __name__ == "__main__":
    unittest.main()
    # import uvicorn
    # uvicorn.run(create_app(), host="0.0.0.0", port=9090)
```

**Comment by KiraPC** [comment] 2021-03-30 21:01
Hi @delijati, thank you for using this library.

To reply to your issue, you are defining "x" as Class Attribute, so that's correct that you can use that variable from the instance of that class. 

If you want to use that variable you should do something like this 'SampleController.x.create()'.

Instead, if you want to define 'x' as Instance Variable, you can declare it in the class __init__ function.

Let me share with you also an useful link where someone can explain better that me this python property.

https://www.toptal.com/python/python-class-attributes-an-overly-thorough-guide

Please, just let me know if I can close the issue.

**Comment by delijati** [comment] 2021-03-30 21:14
No that is not the problem. Both should work `SampleController.x` and `self.x` -> Even if i change `self.x` to `SampleController.x` i get the same error: 
```
AttributeError: 'Depends' object has no attribute 'create'
```

@dmontagu does some magic to get `Depends` working in https://github.com/dmontagu/fastapi-utils/blob/master/fastapi_utils/cbv.py

**Comment by KiraPC** [comment] 2021-03-30 21:18
@delijati Ok, I didn't get the point.

Now I'm writing from my smartphone. 

I take in charge this issue and analyze it tomorrow.

I'll let you know.

**Comment by delijati** [comment] 2021-03-30 21:21
All good thanks for taking the time :)

**Comment by KiraPC** [comment] 2021-03-31 07:22
Hi @delijati 

From my PC the point is more clear.

I also read the fastapi-utils documentation and understood what is your expected behavior.

Since fastapi-router-controller is not a parting of the fastapi-utils CBV class, I didn't thought at this feature when I implemented it.

Anyway, If this could your work, I'll implement it as a new feature in a future version.

I'll do my best to delivery it as soon as possibile, in the meanwhile you can still use the standard fastapi way to declare a dependency.

```python
@controller.resource()
class SampleController:
    x = Depends(get_x)
    @controller.route.get(
        "/", tags=["sample_controller"], summary="return a sample object",
        response_model=SampleObject
    )
    def sample_get_request(
        self,
        id: str = Query(...),
        x = Depends(get_x)
    ):
        print(x.create())
        return SampleObject(id=id)
```

**Comment by delijati** [comment] 2021-03-31 07:25
@KiraPC thanks for taking a look into it :)

**Comment by KiraPC** [comment] 2021-03-31 16:06
@delijati I've create a PR with the enhancement requested. 

Are you able to check if it work before merging it?

Let me explain how I thought this feature should works.

As opposed to fastapi-utils cbv, I don't like to set the dependecies as python attribute class, in order to don't create confusion when you use them.

So, you can define now the dependecies as instance properties in the __init__ function.

```python
from fastapi import APIRouter, Depends
from fastapi_router_controller import Controller

router = APIRouter()
controller = Controller(router)

async def amazing_fn():
    return 'amazing_variable'

@controller.resource()
class ExampleController():
    # you can define in the Controller init some FastApi Dependency and them are automatically loaded in controller methods
    def __init__(self, x: Foo = Depends(amazing_fn)):
        self.x = x
    
    @controller.route.get(
        '/some_aoi', 
        summary='A sample description')
    def sample_api(self):
        print(self.x) # -> amazing_variable
        
        return 'A sample response'
```

Do you think that can solve your problem?

**Comment by delijati** [comment] 2021-03-31 22:12
Nice Thanks. What i see looks like what i was expecting :) I will give it a try after eastern :)

**Comment by KiraPC** [comment] 2021-03-31 22:30
I'll merge the PR tomorrow. So publish on pypi.

**Closed as completed** 2021-04-01 06:59 UTC
Labels: enhancement
