### ISSUE TITLE
Supporting Multi-Parent 

### ISSUE THREAD

**Issue by mhmgad** [KiraPC/fastapi-router-controller#23] opened 2022-02-21 13:24 UTC
First Thank you for the amazing work! the lib is very handy!

I am trying to implement a controller with multiple parents. I found out that the routes in the second parent are not included. Is there a reason behind disabling that?

I need to allow multi-parent to be able to define two sets of routes with different dependencies, then create a class view that combine them and include some extra abstract methods. Later this view will be inherited and implemented. 

```
router = APIRouter()
controller = Controller(router)


def d1(d):
  return d


@controller.resource()
class ParentA():

  def __init__(self, x = Depends(d1)):
    self.x =x

  @controller.router.get('/parent_a_test')
  def get(self):
    print('in parent A')


router2 = APIRouter()
controller2 = Controller(router2)


@controller2.resource()
class ParentB(abc.ABC):

  @controller2.router.get('/parent_b_test')
  def get(self):
      print('in parent B')

  @abc.abstractmethod
  def get_abstract(self):
      pass


router3 = APIRouter()
controller3 = Controller(router3)


@controller3.resource()
class AbstractView(ParentA, ParentB, abc.ABC):

  @controller3.router.get('/get_view')
  def get(self):
    print('abstract view')



router4 = APIRouter(tags=['child'], prefix='/child')
controller4 = Controller(router4)

@controller4.resource()
class ImplChild(AbstractView):

  @controller4.router.get('/Child_test')
   def get_abstract(self):
      print('get_abstract Implemnetation')
```

**Comment by KiraPC** [comment] 2022-02-21 13:56
Hello @mhmgad 

Thanks for using this library, I'm very happy that it is useful.

I've analyzed the problem and I'll solve ASAP, I already have the solution to the problem, I just need some time to test that don't break anything.

**Comment by KiraPC** [comment] 2022-02-22 08:24
@mhmgad The version 0.5.0 should solve the problem.

Please, let me know.

**Comment by mhmgad** [comment] 2022-02-23 08:36
thank you Kira for the the quick fix. I will try it and let you know.
I also wonder, when defining dependencies in the __init__ of the 2 parents, What would be the behavior of the child class?

**Comment by mhmgad** [comment] 2022-02-23 09:17
I tested it and it works!
 However, my idea of defining 2 parent classes, with different dependencies and extend both with a single child class, did not work. All dependencies in all __init__ classes were merged together :(

**Comment by KiraPC** [comment] 2022-02-23 09:20
mmmm I did not thought at this feature. Could you make and example, with desired and actual in a new issue? 

I'm closing this since the problem is solved.

**Closed as completed by KiraPC** 2022-02-23 09:20 UTC
Labels: bug
